# Generated by Django 6.0.1 on 2026-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_smscode_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата согласия'),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Факт принятия юридической оферты.', verbose_name='Согласие на рассылку'),
        ),
    ]
