# Generated by Django 6.0.1 on 2026-01-18 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_consent_date_user_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, help_text='Хранится в открытом виде для сравнения при сбросе.', max_length=255, null=True, verbose_name='Ответ на секретный вопрос'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, help_text='Используется для восстановления доступа.', max_length=255, null=True, verbose_name='Секретный вопрос'),
        ),
    ]
