# Generated by Django 6.0.2 on 2026-02-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_security_answer_user_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата для отправки результатов.', max_length=50, null=True, unique=True, verbose_name='Telegram Chat ID'),
        ),
    ]
