# Generated by Django 6.0.1 on 2026-01-17 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deepseek_api_key', models.CharField(max_length=255)),
                ('sms_api_id', models.CharField(max_length=255)),
                ('short_result_prompt', models.TextField()),
                ('extended_result_prompt', models.TextField()),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
                'verbose_name_plural': 'Глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(choices=[('V1', 'До 11 лет'), ('V2', 'От 12 лет')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=255)),
                ('child_gender', models.CharField(max_length=10)),
                ('child_age', models.IntegerField()),
                ('answers_data', models.JSONField()),
                ('calculated_indices', models.JSONField(default=dict)),
                ('short_interpretation', models.TextField(blank=True)),
                ('extended_interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testing.testsuite')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testsuite')),
            ],
        ),
    ]
