# Generated by Django 6.0.1 on 2026-01-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='deepseek_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='extended_result_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='short_result_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sms_api_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
