# Generated by Django 6.0.1 on 2026-01-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_alter_appconfig_deepseek_api_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат теста', 'verbose_name_plural': 'Результаты тестов'},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': 'Набор тестов', 'verbose_name_plural': 'Наборы тестов'},
        ),
    ]
