# Generated by Django 6.0.1 on 2026-01-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_question_options_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name': 'Настройки API и Промптов', 'verbose_name_plural': 'Настройки API и Промптов'},
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='Нужен для генерации ответов ИИ. Получите его в кабинете DeepSeek.', max_length=255, null=True, verbose_name='Ключ DeepSeek API'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='extended_result_prompt',
            field=models.TextField(blank=True, help_text='Инструкция для ИИ: как составить подробный отчет для продажи доп. услуг.', null=True, verbose_name='Полный промпт (для админа)'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='short_result_prompt',
            field=models.TextField(blank=True, help_text='Инструкция для ИИ: как составить краткий результат после теста.', null=True, verbose_name='Короткий промпт (для пользователя)'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sms_api_id',
            field=models.CharField(blank=True, help_text='Нужен для отправки SMS-кодов. Формат: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX', max_length=255, null=True, verbose_name='API ID SMS.ru'),
        ),
    ]
