# Generated by Django 6.0.1 on 2026-01-17 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_appconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name': 'Настройки системы', 'verbose_name_plural': 'Настройки системы'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Результат тестирования', 'verbose_name_plural': 'Результаты тестирований'},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': 'Набор вопросов', 'verbose_name_plural': 'Наборы вопросов'},
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='deepseek_api_key',
            field=models.CharField(blank=True, help_text='Используется для связи с нейросетью.', max_length=255, null=True, verbose_name='Ключ DeepSeek API'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='extended_result_prompt',
            field=models.TextField(blank=True, help_text='Инструкция ИИ для формирования детального отчета администратору.', null=True, verbose_name='Промпт для полного отчета'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='short_result_prompt',
            field=models.TextField(blank=True, help_text='Инструкция ИИ для формирования результата пользователю.', null=True, verbose_name='Промпт для короткого вывода'),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='sms_api_id',
            field=models.CharField(blank=True, help_text='Необходим для отправки авторизационных SMS.', max_length=255, null=True, verbose_name='API ID SMS.ru'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(help_text="Группа для расчета индексов (например, 'Техника').", max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Определяет очередность вывода вопросов.', verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='question',
            name='suite',
            field=models.ForeignKey(help_text='Набор, к которому относится этот вопрос.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testing.testsuite', verbose_name='Тест'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Утверждение, которое пользователь должен оценить.', verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='answers_data',
            field=models.JSONField(help_text='Список всех вопросов и баллов пользователя.', verbose_name='Данные ответов'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='calculated_indices',
            field=models.JSONField(default=dict, help_text='Средние баллы по каждой категории.', verbose_name='Рассчитанные индексы'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_age',
            field=models.IntegerField(help_text='Указанный в анкете возраст.', verbose_name='Возраст ребёнка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_gender',
            field=models.CharField(help_text='Выбранный пол.', max_length=10, verbose_name='Пол ребёнка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_name',
            field=models.CharField(help_text='Имя, указанное в анкете перед тестом.', max_length=255, verbose_name='Имя ребёнка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='extended_interpretation',
            field=models.TextField(blank=True, help_text='Подробный анализ для администратора.', verbose_name='Полный отчет (ИИ)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='short_interpretation',
            field=models.TextField(blank=True, help_text='Текст, который увидел пользователь.', verbose_name='Краткое заключение (ИИ)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='suite',
            field=models.ForeignKey(help_text='Версия теста, которую прошел ребенок.', on_delete=django.db.models.deletion.PROTECT, to='testing.testsuite', verbose_name='Использованный тест'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(help_text='Аккаунт, с которого пройдено тестирование.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь (родитель)'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Только активные тесты отображаются на сайте.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(help_text="Например: 'Общий профориентационный тест'.", max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='version',
            field=models.CharField(choices=[('V1', 'До 11 лет'), ('V2', 'От 12 лет')], help_text='Определяет, какому пользователю будет показан этот тест.', max_length=2, verbose_name='Возрастная категория'),
        ),
    ]
