# Generated by Django 6.0.1 on 2026-01-17 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_appconfig_options_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='suite',
            field=models.ForeignKey(help_text='Версия теста, которую прошел ребенок.', on_delete=django.db.models.deletion.CASCADE, to='testing.testsuite', verbose_name='Использованный тест'),
        ),
    ]
