# Generated by Django 6.0.1 on 2026-01-18 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_testresult_suite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100, verbose_name='Тип ошибки')),
                ('message', models.TextField(verbose_name='Текст ошибки')),
                ('raw_response', models.TextField(blank=True, null=True, verbose_name='Сырой ответ API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='error_logs', to='testing.testresult')),
            ],
            options={
                'verbose_name': 'Лог ошибок ИИ',
                'verbose_name_plural': 'Логи ошибок ИИ',
            },
        ),
    ]
