# Generated by Django 6.0.1 on 2026-01-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_aierrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='child_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения ребёнка'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='extra_stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='Дополнительная статистика'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя и фамилия родителя'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Контактный номер родителя'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='reliability_level',
            field=models.CharField(default='green', max_length=10, verbose_name='Уровень достоверности'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='reliability_notes',
            field=models.TextField(blank=True, verbose_name='Заметки по достоверности'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='school_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер школы'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='thinking_profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль мышления'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='answers_data',
            field=models.JSONField(verbose_name='Данные ответов'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='calculated_indices',
            field=models.JSONField(default=dict, verbose_name='Рассчитанные индексы'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_age',
            field=models.IntegerField(verbose_name='Возраст (на момент теста)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_gender',
            field=models.CharField(max_length=10, verbose_name='Пол ребёнка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='child_name',
            field=models.CharField(max_length=255, verbose_name='Имя и фамилия ребёнка'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='extended_interpretation',
            field=models.TextField(blank=True, verbose_name='Полный отчет (ИИ)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='short_interpretation',
            field=models.TextField(blank=True, verbose_name='Краткое заключение (ИИ)'),
        ),
    ]
