# Generated by Django 6.0.1 on 2026-01-23 20:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_testresult_child_dob_testresult_extra_stats_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testsuite',
            options={'verbose_name': 'Версия теста', 'verbose_name_plural': 'Версии тестов'},
        ),
        migrations.AddField(
            model_name='testsuite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsuite',
            name='description',
            field=models.TextField(blank=True, help_text='Отображается перед началом вопросов.', verbose_name='Вводный текст (HTML)'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='scale_config',
            field=models.JSONField(blank=True, default=dict, help_text="Пример: {'1': 'Совсем не похоже', '2': 'Скорее не похоже' ...}", verbose_name='Настройки шкалы'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='version',
            field=models.CharField(choices=[('V1', '7-11 лет'), ('V2', '12-18 лет')], default='V1', max_length=10, verbose_name='Версия'),
        ),
    ]
