# Generated by Django 6.0.1 on 2026-01-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_remove_appconfig_extended_result_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='closing_text',
            field=models.TextField(blank=True, help_text='Отображается в конце теста или под кнопкой отправки.', verbose_name='Заключительный текст (HTML)'),
        ),
    ]
