# Generated by Django 6.0.1 on 2026-01-26 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_remove_appconfig_extended_result_prompt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="Например: 'Какое у тебя хобби?' или 'Твоя мечта?'", max_length=255, verbose_name='Текст вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_questions', to='testing.testsuite', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Финальный вопрос',
                'verbose_name_plural': 'Финальные вопросы (после теста)',
                'ordering': ['order'],
            },
        ),
    ]
