# Generated by Django 6.0.1 on 2026-01-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_finalquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='version',
            field=models.CharField(choices=[('V1', '7-11 лет'), ('V2', '12-17 лет'), ('V3', '18+ лет (Взрослые)')], default='V1', max_length=10, verbose_name='Версия'),
        ),
    ]
