# Generated by Django 6.0.2 on 2026-02-10 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_alter_testsuite_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Поддерживаются PDF, DOCX, XLSX, TXT', upload_to='knowledge_base/', verbose_name='Файл документа')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'База знаний (RAG)',
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Профориентационное тестирование', max_length=255, verbose_name='Заголовок страницы')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок (описание под заголовком)')),
                ('main_image', models.ImageField(blank=True, help_text='Используется, если не указано видео.', null=True, upload_to='landing/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(blank=True, help_text='Например: https://www.youtube.com/watch?v=ID_ВИДЕО', null=True, verbose_name='Ссылка на видео (YouTube)')),
                ('content_html', models.TextField(blank=True, help_text='Здесь можно разместить любую информацию.', verbose_name='Основной контент (HTML)')),
                ('button_text', models.CharField(default='Пройти тест', max_length=50, verbose_name='Текст на кнопке')),
            ],
            options={
                'verbose_name': 'Конструктор лендинга',
                'verbose_name_plural': 'Конструктор лендинга',
            },
        ),
        migrations.CreateModel(
            name='UtmCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кампании')),
                ('utm_source', models.CharField(max_length=100, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True, verbose_name='utm_campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'UTM-метка',
                'verbose_name_plural': 'UTM-метки',
            },
        ),
        migrations.RemoveField(
            model_name='appconfig',
            name='sms_api_id',
        ),
        migrations.AddField(
            model_name='aierrorlog',
            name='model_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Использованная модель'),
        ),
        migrations.AddField(
            model_name='aierrorlog',
            name='temp_used',
            field=models.FloatField(blank=True, null=True, verbose_name='Температура'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='admin_notification_ids',
            field=models.TextField(blank=True, help_text='Введите chat_id администраторов через запятую. Им будут приходить уведомления о заявках.', null=True, verbose_name='ID администраторов (Telegram)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ai_max_tokens_chat',
            field=models.PositiveIntegerField(default=4000, help_text='Лимит токенов для моделей типа Chat. Рекомендуется: 4000, максимум 8000.', verbose_name='Max Tokens (Chat)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='ai_max_tokens_reasoner',
            field=models.PositiveIntegerField(default=32000, help_text='Лимит токенов для моделей типа thinking-mode. Рекомендуется: 32000, максимум 64000.', verbose_name='Max Tokens (Thinking-mode)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Например: support@proftest.ru', max_length=255, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='support_instagram',
            field=models.CharField(blank=True, help_text='Например: https://instagram.com/username', max_length=255, null=True, verbose_name='Instagram (ссылка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='support_messenger_max',
            field=models.CharField(blank=True, help_text='Введите ссылку на чат в мессенджере MAX', max_length=255, null=True, verbose_name='Мессенджер MAX (ссылка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='support_whatsapp',
            field=models.CharField(blank=True, help_text='Например: 79001234567 или https://wa.me/79001234567', max_length=255, null=True, verbose_name='WhatsApp (номер или ссылка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telegram_bot_name',
            field=models.CharField(blank=True, help_text='Например: Humanprofibot. Нужно для формирования ссылки.', max_length=255, null=True, verbose_name='Имя Telegram бота (без @)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Получите у @BotFather. Пример: 123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11', max_length=255, null=True, verbose_name='Токен Telegram бота'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='contact_detail',
            field=models.CharField(blank=True, help_text='Email или ссылка на профиль', max_length=255, verbose_name='Контактные данные (Email/MAX)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='contact_method',
            field=models.CharField(choices=[('telegram', 'Telegram Бот'), ('email', 'E-mail'), ('max', 'Мессенджер MAX'), ('view_only', 'Только просмотр')], default='view_only', max_length=20, verbose_name='Способ получения отчета'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='manager_info',
            field=models.TextField(blank=True, verbose_name='Информация для менеджера (ИИ)'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='ai_model_profile',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek (Chat)'), ('deepseek-reasoner', 'DeepSeek (Thinking-mode)')], default='deepseek-chat', max_length=50, verbose_name='Модель для профиля'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='ai_model_report',
            field=models.CharField(choices=[('deepseek-chat', 'DeepSeek (Chat)'), ('deepseek-reasoner', 'DeepSeek (Thinking-mode)')], default='deepseek-reasoner', max_length=50, verbose_name='Модель для отчетов'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='ai_temperature',
            field=models.FloatField(default=0.1, verbose_name='Температура AI (0.0 - 1.0)'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='is_admin_only',
            field=models.BooleanField(default=False, verbose_name='Только для админов (Тестовый режим)'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='manager_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='User Prompt для менеджера'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='profile_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='User Prompt для профиля'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='profile_system_prompt',
            field=models.TextField(default='Ты — эксперт по профориентации. Определи профиль мышления на основе данных.', verbose_name='System Prompt для профиля'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='report_system_prompt',
            field=models.TextField(default='Ты — профессиональный психолог-диагност. Пишешь подробный отчет для ребенка.', verbose_name='System Prompt для отчетов'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_answers_data',
            field=models.BooleanField(default=False, verbose_name='Все ответы и вопросы {{answers_data}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_child_info',
            field=models.BooleanField(default=True, verbose_name='Возраст {{child_age}} и пол {{child_gender}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_child_name',
            field=models.BooleanField(default=True, verbose_name='Имя ребенка {{child_name}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_extra_data',
            field=models.BooleanField(default=True, verbose_name='Дополнительные вопросы {{extra_data}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_indices',
            field=models.BooleanField(default=True, verbose_name='Результаты формул {{indices}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_parent_info',
            field=models.BooleanField(default=False, verbose_name='Данные родителя {{parent_name}}, {{parent_phone}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_project_info',
            field=models.BooleanField(default=True, verbose_name='Данные проекта {{project_name}}, {{website}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_rag_context',
            field=models.BooleanField(default=True, verbose_name='База знаний (RAG) {{rag_context}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_reliability',
            field=models.BooleanField(default=True, verbose_name='Достоверность {{reliability}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_school_info',
            field=models.BooleanField(default=True, verbose_name='Школа и класс {{school}}, {{grade}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_test_meta',
            field=models.BooleanField(default=True, verbose_name='Метаданные теста {{test_date}}, {{test_version}}'),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='send_thinking_profile',
            field=models.BooleanField(default=True, verbose_name='Профиль мышления {{profile}}'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='closing_text',
            field=models.TextField(blank=True, verbose_name='Заключительный текст (HTML)'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='description',
            field=models.TextField(blank=True, verbose_name='Вводный текст (HTML)'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='extended_result_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='User Prompt для полного отчета'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='scale_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Настройки шкалы'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='short_result_prompt',
            field=models.TextField(blank=True, null=True, verbose_name='User Prompt для краткого отчета'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='version',
            field=models.CharField(choices=[('V1', '5-11 лет'), ('V2', '12-17 лет'), ('V3', '18+ лет (Взрослые)')], default='V1', max_length=10, verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='ProfileRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Название профиля')),
                ('description', models.TextField(verbose_name='Описание профиля')),
                ('vector_development', models.TextField(verbose_name='Вектор развития (1-2 года)')),
                ('top_professions', models.TextField(verbose_name='Топ-5 профессий (с описанием)')),
                ('action_plan', models.TextField(verbose_name='План действий на 3 месяца')),
                ('zones_attention', models.TextField(verbose_name='Зоны внимания (что может быть сложным)')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='testing.testsuite', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Рекомендация профиля',
                'verbose_name_plural': 'Рекомендации профилей',
            },
        ),
        migrations.CreateModel(
            name='ReliabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('inconsistency', 'Противоречивость (Разница баллов)'), ('both_high', 'Противоречивость (Оба высокие - Ловушка)'), ('social_desirability', 'Социальная желательность (Шкала лжи)'), ('fixed_answer', 'Проверочный вопрос (Внимание)'), ('monotony', 'Однообразие ответов (Случайный выбор)')], help_text='Выберите, что именно мы проверяем.', max_length=50, verbose_name='Тип проверки')),
                ('question_indices', models.CharField(blank=True, help_text='Введите номера вопросов через запятую.', max_length=100, null=True, verbose_name='Номера вопросов')),
                ('threshold', models.FloatField(default=0, help_text='Порог срабатывания правила.', verbose_name='Порог срабатывания')),
                ('error_message', models.CharField(help_text='Что увидит администратор в отчете.', max_length=255, verbose_name='Текст замечания')),
                ('severity', models.CharField(choices=[('yellow', 'Предупреждение (Желтый)'), ('red', 'Недостоверно (Красный)')], default='yellow', help_text='Для V1 влияет на цвет сразу. Для V2/V3 — просто фиксирует ошибку.', max_length=10, verbose_name='Уровень критичности')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reliability_rules', to='testing.testsuite', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Правило достоверности',
                'verbose_name_plural': 'Правила достоверности',
            },
        ),
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название индекса')),
                ('formula', models.CharField(help_text='Используйте [q1], [q2] и т.д. Пример: ([q1]+[q5])/2 * 25. Это сложит баллы за 1 и 5 вопросы, найдет среднее и переведет в 100-балльную шкалу.', max_length=255, verbose_name='Формула расчета')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='testing.testsuite', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Категория (Индекс)',
                'verbose_name_plural': 'Категории (Индексы)',
            },
        ),
        migrations.CreateModel(
            name='ProfileMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=100, verbose_name='Название профиля (напр. СТРАТЕГ)')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_matrix', to='testing.testsuite', verbose_name='Тест')),
                ('index_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_index_1', to='testing.testcategory', verbose_name='Индекс 1')),
                ('index_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_index_2', to='testing.testcategory', verbose_name='Индекс 2')),
            ],
            options={
                'verbose_name': 'Матрица профиля',
                'verbose_name_plural': 'Матрица профилей',
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='testing.testcategory', verbose_name='Категория (Индекс)'),
        ),
        migrations.CreateModel(
            name='UserUtm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='utm_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UTM-данные пользователя',
                'verbose_name_plural': 'UTM-данные пользователей',
            },
        ),
    ]
