# Generated by Django 6.0.2 on 2026-02-18 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_knowledgebasedocument_landingpage_utmcampaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название локации')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
            ],
            options={
                'verbose_name': 'Локация (Регион)',
                'verbose_name_plural': 'Локации (Регионы)',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appconfig',
            name='is_payment_enabled',
            field=models.BooleanField(default=False, help_text='Если включено, полный отчет доступен только после оплаты.', verbose_name='Включить платный режим'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='payment_price',
            field=models.PositiveIntegerField(default=0, help_text='Сумма в рублях, которую должен оплатить клиент.', verbose_name='Стоимость полного отчета (RUB)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tochka_client_id',
            field=models.CharField(blank=True, help_text='ID приложения. Нужен для проверки вебхуков и OAuth.', max_length=255, null=True, verbose_name='Client ID (Точка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tochka_client_secret',
            field=models.CharField(blank=True, help_text='Секрет приложения. Нужен, если будете настраивать автоматическое получение токена.', max_length=255, null=True, verbose_name='Client Secret (Точка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tochka_customer_code',
            field=models.CharField(blank=True, help_text='Уникальный код клиента в системе банка. Можно получить через API или в ЛК.', max_length=255, null=True, verbose_name='Customer Code (Точка)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tochka_jwt_token',
            field=models.TextField(blank=True, help_text='Сгенерируйте в интернет-банке Точки (Интеграции и API -> JWT).', null=True, verbose_name='JWT Токен Точка Банка'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='tochka_merchant_id',
            field=models.CharField(blank=True, help_text='Идентификатор торговой точки (15 цифр). Нужен для эквайринга.', max_length=255, null=True, verbose_name='Merchant ID (Точка)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен полный отчет'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='payment_operation_id',
            field=models.CharField(blank=True, help_text='operationId из банка', max_length=255, null=True, verbose_name='ID операции оплаты (Точка)'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(default='Основной тест', max_length=255, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='version',
            field=models.CharField(choices=[('V0', 'Дошкольники (5-7 лет)'), ('V1', 'Школьники (7-11 лет)'), ('V2', 'Подростки (12-17 лет)'), ('V3', 'Взрослые (18+ лет)')], default='V1', max_length=10, verbose_name='Версия'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testing.location', verbose_name='Местонахождение'),
        ),
    ]
