# Generated by Django 6.0.2 on 2026-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0017_location_appconfig_is_payment_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='example_full_report',
            field=models.FileField(blank=True, help_text='Загрузите файл примера. Если не загружено, кнопка может не работать.', null=True, upload_to='examples/', verbose_name='Пример полного отчета (PDF)'),
        ),
    ]
